name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Test
      uses: actions/bin/bats@master
      with:
        args: test/*.bats